### ISSUE TITLE
Overview model AI recommendation

### ISSUE THREAD

**Issue by phamtiep** [phamtiep/recify-web-player#11]
Tổng quan về model AI sử dụng

**Comment by VietAnh-AI2-UET** [comment]
Item-item collaborative filtering sử dụng model KNN với thuật toán cosine similarity. Sử dụng dữ liệu về số lượt nghe của từng user đối với từng bài nhạc để tính toán sự tương đồng giữa các bài nhạc bằng thuật toán cosine similarity. Từ đó đề xuất các bài nhạc có sự tương đồng cao với bài nhạc đang nghe.
